// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmRtGyZBhsMg94kA529tHYROchui9V_rY',
    appId: '1:563773216975:web:d823c744742a7339c67fba',
    messagingSenderId: '563773216975',
    projectId: 'uni-book-d5548',
    authDomain: 'uni-book-d5548.firebaseapp.com',
    storageBucket: 'uni-book-d5548.firebasestorage.app',
    measurementId: 'G-XE00WNHP46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZCPL4_XI5BDCGXLUof_t8sT8JRstoAl8',
    appId: '1:563773216975:android:72dcafaf243d7e7ac67fba',
    messagingSenderId: '563773216975',
    projectId: 'uni-book-d5548',
    storageBucket: 'uni-book-d5548.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE6TyR3HHPfUQ6KQxcwRkAwf3PwIIvh-k',
    appId: '1:563773216975:ios:3aedeb5f310563b3c67fba',
    messagingSenderId: '563773216975',
    projectId: 'uni-book-d5548',
    storageBucket: 'uni-book-d5548.firebasestorage.app',
    iosBundleId: 'com.example.uniBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE6TyR3HHPfUQ6KQxcwRkAwf3PwIIvh-k',
    appId: '1:563773216975:ios:3aedeb5f310563b3c67fba',
    messagingSenderId: '563773216975',
    projectId: 'uni-book-d5548',
    storageBucket: 'uni-book-d5548.firebasestorage.app',
    iosBundleId: 'com.example.uniBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmRtGyZBhsMg94kA529tHYROchui9V_rY',
    appId: '1:563773216975:web:6d68855f8f7d9f54c67fba',
    messagingSenderId: '563773216975',
    projectId: 'uni-book-d5548',
    authDomain: 'uni-book-d5548.firebaseapp.com',
    storageBucket: 'uni-book-d5548.firebasestorage.app',
    measurementId: 'G-GB0HVW8DE4',
  );
}
